name: PR Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Serviço do Strapi para os testes
      strapi:
        name: strapi
        # Usa o Dockerfile local
        image: local/strapi-app:test
        ports:
          - 1337:1337
        env:
          NODE_ENV: test
          DATABASE_FILENAME: .tmp/data.db
        # Dá tempo para o Strapi iniciar
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:1337/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3
    
    # Constroi a imagem Docker localmente
    - name: Build Docker image
      run: |
        docker build -t local/strapi-app:test .
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    # Aguarda o serviço Strapi estar pronto
    - name: Wait for Strapi
      run: |
        timeout 180 bash -c 'until curl -s http://localhost:1337/; do sleep 5; done' || \
          (docker logs strapi && exit 1)
    
    - name: Run E2E Tests
      run: pnpm test:e2e
      env:
        STRAPI_URL: http://localhost:1337
