name: PR Checks

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      id: build
      run: |
        docker build -t local/strapi-app:test .
        echo "image-tag=local/strapi-app:test" >> $GITHUB_OUTPUT
    
    - name: Save Docker image
      run: docker save -o strapi-image.tar local/strapi-app:test
      
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: strapi-image
        path: strapi-image.tar
        retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    
    services:
      # Serviço do Strapi para os testes
      strapi:
        image: local/strapi-app:test
        ports:
          - 1337:1337
        env:
          NODE_ENV: test
          DATABASE_FILENAME: .tmp/data.db
        # Dá tempo para o Strapi iniciar
        options: >-
          --name strapi
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:1337/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3
    
    - name: Download Docker image
      uses: actions/download-artifact@v3
      with:
        name: strapi-image
        path: ./docker-images
    
    - name: Load Docker image
      run: |
        docker load -i ./docker-images/strapi-image.tar
        docker images
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    # Aguarda o serviço Strapi estar pronto
    - name: Wait for Strapi
      run: |
        timeout 180 bash -c 'until curl -s http://localhost:1337/; do sleep 5; done' || \
          (docker logs strapi && exit 1)
    
    - name: Run E2E Tests
      run: pnpm test:e2e
      env:
        STRAPI_URL: http://localhost:1337
